version: 1.0.{build}

image: Visual Studio 2019

environment:
  NODE_ENV: production
  ELECTRON_VERSION: 28.1.0  # Update to your Electron version

install:
  - npm install

build:
  - npm run dist  # Assumes your package.json has the "dist" script set up to package the app

artifacts:
  - path: dist\*  # Path where packaged app is located
